title            : "All The Languages"
description      : >-
  Hi! I'm <span class="tooltip" title="It's pronounced
  [pʌpɛin].">Pepijn</span>. I study natural languages, programming
  languages and logical languages. Basically, all the languages.
url              : 'https://pepijnkokke.github.io'
baseurl          : ''
google_analytics : 'UA-74596735-1'
disqus_shortname : 'pepijnkokke'

author:
  name              : 'Pepijn Kokke'
  github_username   : pepijnkokke

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'


destination : _site
paginate    : 10
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

kramdown:
  input: GFM
  hard_wrap: false

gems    : ['jekyll-paginate']
exclude : ['Gemfile', 'Gemfile.lock', 'Rakefile', 'tasks/', '*.lagda', '*.agdai']
